Update editor immediately for native insertion events
textioHQ/draft-js pull request #24
Opened 2017-01-31 22:27 UTC by max-winderbaum

2017-02-01 13:31 UTC, colinjeanne requested changes

2017-02-01 13:31 UTC, colinjeanne commented on src/component/handlers/edit/editOnBeforeInput.js
>      // change the inserted text, we wait until the text is actually inserted
Make sure to update this comment since it's no longer accurate.

2017-02-01 16:08 UTC, max-winderbaum commented
There's one other problem I've noticed, and that's that in IE editor._usingNativeRendering will just set true and never flip. I don't think there is any performance problem with this, it just is worth mentioning.

2017-02-01 16:27 UTC, max-winderbaum commented
A third problem is that autocorrect changes are broken because they don't get to fall through editOnInput. This is not a change from the old way of doing things though - it's just another problem to solve.

2017-02-01 16:30 UTC, max-winderbaum commented on src/component/handlers/edit/editOnBeforeInput.js
>      // change the inserted text, we wait until the text is actually inserted
done

2017-02-02 02:10 UTC, AnilRedshift commented on src/component/handlers/edit/editOnInput.js
> +      return;
What's the reason for not clearing `_waitingOnInput` here?

2017-02-02 04:32 UTC, colinjeanne requested changes

2017-02-02 04:32 UTC, colinjeanne commented on src/component/handlers/edit/editOnBeforeInput.js
> +        editOnInput(editor);
One of the major differences between my fix and flarnie's fix was that mine called `editOnInput` and hers didn't. Mine also caused https://github.com/textioHQ/editor/issues/582.

Have we validated that this doesn't regress 582? If it doesn't, why doesn't it?

2017-02-02 17:45 UTC, colinjeanne commented on src/component/handlers/edit/editOnBeforeInput.js
> +        editOnInput(editor);
It looks like I can repro seeing the caret lag behind where typing occurs for documents with a lot of highlights. This is fairly difficult to get a repro of and the typing experience in this case is so slow that the caret is the least of my worries.

2017-02-06 13:50 UTC, colinjeanne approved these changes

2017-02-06 13:50 UTC, colinjeanne commented
:ship: pending testing

2017-02-08 00:50 UTC, merged