Add `silentlyUpdate` method
textioHQ/draft-js pull request #75
Opened 2018-08-09 22:27 UTC by david-davidson

[EN-1250](https://textio.atlassian.net/browse/EN-1250) exposed a code path where Draft plugins can trigger change events in `editor` without ever passing through `DraftEditor` and updating `this._latestEditorState`. Trouble is, [`editor` treats `this._latestEditorState` as a source of truth](https://github.com/textioHQ/editor/blob/master/src/TextioEditor/TextioEditor.js#L371-L375), so plugin changes can cause problems with (temporarily) stale state.

This PR adds a new `silentlyUpdate` method—like `update`, it updates `this._latestEditorState`, but without calling `this.onChange`. Upstream code (in either `draft-js-plugins-editor` or `editor` itself) can call this to make sure state is consistent.

2018-08-09 22:29 UTC, max-winderbaum commented
What does this get us over just setting `_latestEditorState` ourselves?

2018-08-09 22:29 UTC, david-davidson commented
Exactly nothing aside from not having to modify private-looking properties across repo boundaries. /shrug

2018-08-09 22:31 UTC, max-winderbaum commented
I'm kind of torn here because I understand your logic, but we also want to keep our fork's diff from facebook's draft as small as possible...

Your call - I'll approve this!

2018-08-09 22:31 UTC, max-winderbaum approved these changes

2018-08-09 22:35 UTC, david-davidson commented
_Without_ this, I could imagine someone trying to understanding changes to `this._latestEditorState` and feeling crazy cuz "the only place it's ever updated is `this.update`!" Worth it to signal that _other repos_ might be reaching in and making changes, IMO.

2018-08-09 22:41 UTC, max-winderbaum commented
That argument definitely tips me - Let's do it!

2018-08-10 00:05 UTC, ShannonLCapper requested changes
I have just learned that we're supposed to be making PRs to `release`, not `master`

2018-08-10 00:10 UTC, closed without merging